### ISSUE TITLE
Picard Collect Sequencing Artifact Metrics Failed

### ISSUE THREAD

**Issue by madison-leask** [madison-leask/Pipeline-Project#2]
**Tool standard error:** 
/usr/local/bin/picard: line 5: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/050/027/50027224/_job_tmp -Xmx7g -Xms256m
17:02:00.979 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/picard-2.18.2-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu May 11 17:02:01 GMT 2023] CollectSequencingArtifactMetrics MINIMUM_QUALITY_SCORE=30 MINIMUM_MAPPING_QUALITY=20 MINIMUM_INSERT_SIZE=30 MAXIMUM_INSERT_SIZE=600 INCLUDE_UNPAIRED=false INCLUDE_DUPLICATES=false CONTEXT_SIZE=1 INPUT=MarkDuplicates_on_data_8__BAM OUTPUT=OutPut ASSUME_SORTED=false VALIDATION_STRINGENCY=LENIENT REFERENCE_SEQUENCE=/cvmfs/data.galaxyproject.org/managed/picard_index/apiMel4/apiMel4.fa    INCLUDE_NON_PF_READS=false TANDEM_READS=false USE_OQ=true STOP_AFTER=0 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu May 11 17:02:01 GMT 2023] picard.analysis.artifacts.CollectSequencingArtifactMetrics done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=257425408
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequence dictionaries are not the same size (25, 5321)
	at htsjdk.samtools.util.SequenceUtil.assertSequenceListsEqual(SequenceUtil.java:237)
	at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:320)
	at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:306)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:107)
	at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:84)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

**Tool exit code:** 1
**Job messages:** { "code_desc": "", "desc": "Fatal error: Exit code 1 ()", "error_level": 3, "exit_code": 1, "type": "exit_code" }

**Comment by madison-leask** [comment]
Looking at the settings for this tool, I realise that I had not defined the correct reference genome. I have updated the settings to feed in the dataset with hg19 into this tool.

**Comment by madison-leask** [comment]
In order to re-run the part of this tool and the MultiQC step downstream without having to queue the entire the pipeline I have created a branch version of the pipeline which uses the datasets created from the earlier part of the pipeline as inputs to these tools and run this separately.

**Comment by madison-leask** [comment]
**Tool standard error:**
/usr/local/bin/picard: line 5: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/050/030/50030113/_job_tmp -Xmx7g -Xms256m
18:06:48.782 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/picard-2.18.2-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu May 11 18:06:48 GMT 2023] CollectSequencingArtifactMetrics MINIMUM_QUALITY_SCORE=30 MINIMUM_MAPPING_QUALITY=20 MINIMUM_INSERT_SIZE=30 MAXIMUM_INSERT_SIZE=600 INCLUDE_UNPAIRED=false INCLUDE_DUPLICATES=false CONTEXT_SIZE=1 INPUT=MarkDuplicates_on_data_8__BAM OUTPUT=OutPut ASSUME_SORTED=false VALIDATION_STRINGENCY=LENIENT REFERENCE_SEQUENCE=localref.fa    INCLUDE_NON_PF_READS=false TANDEM_READS=false USE_OQ=true STOP_AFTER=0 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu May 11 18:06:52 GMT 2023] picard.analysis.artifacts.CollectSequencingArtifactMetrics done. Elapsed time: 0.06 minutes.
Runtime.totalMemory()=910688256
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: Record contains library that is missing from header: UnknownLibrary
	at picard.analysis.artifacts.CollectSequencingArtifactMetrics.acceptRead(CollectSequencingArtifactMetrics.java:245)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:145)
	at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:84)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

**Tool exit code:** 1
**Job messages:** { "code_desc": "", "desc": "Fatal error: Exit code 1 ()", "error_level": 3, "exit_code": 1, "type": "exit_code" }

**Comment by madison-leask** [comment]
Troubleshooting this error lead me to a source (https://www.biostars.org/p/439725/) which suggests that this error is due to read groups (RG) missing in the BAM file header. I looked at the BAM file header and it seems that there is no RG defined. I am going to attempt to use a tool in Galaxy to add RG:ID to the BAM file, derived from the sequencing tag in the FASTQ files.

**Comment by madison-leask** [comment]
**Tool standard error:**
/usr/local/bin/picard: line 5: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/050/031/50031134/_job_tmp -Xmx7g -Xms256m
ERROR: Option 'RGSM' is required.

USAGE: AddOrReplaceReadGroups [options]

Documentation: http://broadinstitute.github.io/picard/command-line-overview.html#AddOrReplaceReadGroups

Assigns all the reads in a file to a single new read-group.

This tool accepts INPUT BAM and SAM files or URLs from the Global Alliance for Genomics and Health (GA4GH)
(http://ga4gh.org/#/documentation).

Usage example:

java -jar picard.jar AddOrReplaceReadGroups \
I=input.bam \
O=output.bam \
RGID=4 \
RGLB=lib1 \
RGPL=illumina \
RGPU=unit1 \
RGSM=20


Caveats

The value of the tags must adhere (according to the SAM-spec (https://samtools.github.io/hts-specs/SAMv1.pdf)) with the
regex '^[ -~]+$'</code> (one or more characters from the ASCII range 32 through 126). In particular <Space> is the only
non-printing character allowed.

The program enables only the wholesale assignment of all the reads in the INPUT to a single read-group. If your file
already has reads assigned to multiple read-groups, the original RG value will be lost. 

For more information about read-groups, see the GATK Dictionary entry.
(https://www.broadinstitute.org/gatk/guide/article?id=6472)
Version: 2.18.2-SNAPSHOT


Options:

--help
-h                            Displays options specific to this tool.

--stdhelp
-H                            Displays options specific to this tool AND options common to all Picard command line
                              tools.

--version                     Displays program version.

INPUT=String
I=String                      Input file (BAM or SAM or a GA4GH url).  Required. 

OUTPUT=File
O=File                        Output file (BAM or SAM).  Required. 

SORT_ORDER=SortOrder
SO=SortOrder                  Optional sort order to output in. If not supplied OUTPUT is in the same order as INPUT. 
                              Default value: null. Possible values: {unsorted, queryname, coordinate, duplicate,
                              unknown} 

RGID=String
ID=String                     Read-Group ID  Default value: 1. This option can be set to 'null' to clear the default
                              value. 

RGLB=String
LB=String                     Read-Group library  Required. 

RGPL=String
PL=String                     Read-Group platform (e.g. illumina, solid)  Required. 

RGPU=String
PU=String                     Read-Group platform unit (eg. run barcode)  Required. 

RGSM=String
SM=String                     Read-Group sample name  Required. 

RGCN=String
CN=String                     Read-Group sequencing center name  Default value: null. 

RGDS=String
DS=String                     Read-Group description  Default value: null. 

RGDT=Iso8601Date
DT=Iso8601Date                Read-Group run date  Default value: null. 

RGKS=String
KS=String                     Read-Group key sequence  Default value: null. 

RGFO=String
FO=String                     Read-Group flow order  Default value: null. 

RGPI=Integer
PI=Integer                    Read-Group predicted insert size  Default value: null. 

RGPG=String
PG=String                     Read-Group program group  Default value: null. 

RGPM=String
PM=String                     Read-Group platform model  Default value: null. 

**Tool exit code:** 1
**Job messages:** { "code_desc": "", "desc": "Fatal error: Exit code 1 ()", "error_level": 3, "exit_code": 1, "type": "exit_code" }

**Comment by madison-leask** [comment]
Changed settings on AddOrReplaceReadGroups to auto-assign sample name (RGSM)
